apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-api
  namespace: otel-demo
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: jorturfer/otel-webapi:14
        env:
        - name: RABBITMQ_HOSTNAME
          value: rabbitmq-cluster.otel-demo
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: OTEL_COLLECTOR_URL
          value: http://opentelemetry-collector.otel-demo:4317
---
apiVersion: v1
kind: Service
metadata:
  name: otel-api
  namespace: otel-demo
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000