apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-worker
  namespace: otel-demo
  labels:
    app: worker
spec:
  # replicas: 1   # Not needed with SO/HPA
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: jorturfer/otel-worker:19
        env:
        - name: RABBITMQ_HOSTNAME
          value: rabbitmq-cluster.otel-demo
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: OTEL_COLLECTOR_URL
          value: http://opentelemetry-collector.otel-demo:4317
---
apiVersion: v1
kind: Service
metadata:
  name: otel-worker
  namespace: otel-demo
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: otel-worker-so
#   namespace: otel-demo
# spec:
#   scaleTargetRef:
#     name:          otel-worker
#   pollingInterval:  15
#   cooldownPeriod:   60
#   minReplicaCount:  0
#   maxReplicaCount:  3
#   fallback:
#     failureThreshold: 3
#     replicas: 3
#   triggers:
#   - type: rabbitmq
#     metadata:
#       host: http://guest:guest@rabbitmq-cluster.otel-demo:15672
#       mode: QueueLength 
#       value: "10" 
#       queueName: TestQueue
#       vhostName: /
